trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: npm install -g @vue/cli
  displayName: 'Install Vue'

- script: npm install
  displayName: 'Install NPM Packages'

- script: npm run build
  displayName: 'Build for Produção'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
  displayName: 'Publishing Artifacts'

